### ISSUE TITLE
Close stop Kodi play games

### ISSUE THREAD

**Issue by FregrinZ** [aanderse/plugin.program.steam.library#10]
Anyway close Kodi whilst in a steam game and then reopen after ? On occasion will interfere as controller somehow send input to Kodi and steam game at same time.

**Comment by aanderse** [comment]
What window manager are you using?

**Comment by FregrinZ** [comment]
just have kodi as shell

**Comment by aanderse** [comment]
I highly recommend running kodi with a window manager like openbox if you ever want to launch any application other than kodi during your session.

I used to run a straight kodi environment but found to many problems when launching other apps. Killing kodi is a solution... but not the best solution. A window manager like openbox is great because you'll never see it and it will make everything pretty much just work.

That being said... there are some other kodi+steam plugins out there that do this among other things and I'm pretty interested I eventually merging with them as it's kinda silly to have n different kodi+steam plugins which have overlapping functionality.

For now I'll close as a won't fix, recommending you install openbox, but in the future it might happen.

**Comment by FregrinZ** [comment]
do you have link for this openbox, I assume its windows 10 applicarion

**Comment by aanderse** [comment]
Are you not running Linux?

I'd you're taking Windows I can't really say much as I don't know much about it. I didn't think it was possible to run Windows without a window manager.

**Comment by FregrinZ** [comment]
you can go into regedit and instead of running windows explorer, tell it to run steam big picture or kodi.

For example, https://steamcommunity.com/groups/bigpicture/discussions/1/864958451556578063/
