### ISSUE TITLE
Uninstalled games shown in "Installed games"

### ISSUE THREAD

**Issue by azumukupoe** [aanderse/plugin.program.steam.library#17]
games once installed but uninstalled now are shown in "Installed games"

**Comment by aanderse** [comment]
@azumukupoe Windows or Linux? Most recent version of `plugin.program.steam.library` plugin? Thank you for reporting.

**Comment by azumukupoe** [comment]
>Windows or Linux?

Windows 10

>Most recent version of `plugin.program.steam.library` plugin?

Yes

**Comment by aanderse** [comment]
Unfortunately I don't have any computers running Windows... Maybe @mcfarkleberg might have some ideas :man_shrugging:

**Comment by AmineI** [comment]
Just found this add-on, and I noticed the same issue on Windows.

After looking into it a bit, I noticed that the linux logic in `get_registry_values` only return games with "installed"==1 in the vdf file, if I understood this correctly (I'm a bit confused with the function's name but it looks like the code in main.py is expecting a dictionary of installed games ids as a return value for that one.)

(Relevant Linux logic : )
```Python
vdf = vdf_parse(file, {})
apps = vdf['Registry']['HKCU']['Software']['Valve']['Steam']['Apps']

# apparently case of 'installed' differs depending on ... ?
# i'm sure if i were a python programmer this would look nicer
app_dict = dict((k, v) for (k, v) in apps.iteritems() if ({k.lower(): v for k, v in v.items()}.get('installed', '0') == '1'))
```

I don't have one of these vdf files at hand to examine their structure since I'm on Windows, but that's what I suppose, please correct me if I'm wrong.

On the other hand, on Windows it returns anything that has a value, along with its value, like the function's name would imply. Thus returning games that have `installed=0`, ie that are not currently installed.
I'll open a small PR with a fix to make the Windows logic identical to the Linux logic, but this is a case where I believe renaming the function or refactoring it could be helpful.
