### ISSUE TITLE
steam widget landscape blue overlayed?

### ISSUE THREAD

**Issue by FregrinZ** [aanderse/plugin.program.steam.library#6]
![img_0042](https://user-images.githubusercontent.com/16095651/39966457-0b956ace-56a4-11e8-81a6-18755211dad5.jpg)

why does landscape look like this please?

**Comment by aanderse** [comment]
i believe that is the fanart provided by steam.

**Comment by aanderse** [comment]
I checked and this is the fanart provided by Steam. For example:

http://cdn.akamai.steamstatic.com/steam/apps/400/page_bg_generated_v6b.jpg

If you find a different (and consistent) url that Steam uses to provide better fanart I'd definitely be up for using that.

Let me know if you can find anything.

**Comment by FregrinZ** [comment]
No idea sorry, did find this but possibly of no use.

[https://gaming.stackexchange.com/questions/40879/how-does-steam-set-a-games-background-in-the-library](url)

**Comment by aanderse** [comment]
the resolution of that image is 460x215 which would look horrible on 1080p and up resolutions. also, the aspect ratio is way off.

**Comment by AmineI** [comment]
This could be fixed by #20 which uses 

https://steamcdn-a.akamaihd.net/steam/apps/220440/library_hero.jpg

https://steamcdn-a.akamaihd.net/steam/apps/400/library_hero.jpg

The images are high quality - they are too large however, so it is automatically cropped by Kodi. In my PR I fallback to header.jpg though for the old games that don't provide it, which definitely looks horrible on HD resolutions. Want me to revert that behavior to fallback to the blue thingy instead ?
