### ISSUE TITLE
plugin crashes when there are no games in Steam library

### ISSUE THREAD

**Issue by aanderse** [aanderse/plugin.program.steam.library#9]
Also crashes when you haven't played a game recently and you view the recently played games menu.

The fix is a simple null check.

**Comment by AmineI** [comment]
Obtaining the dictionary value with `dict.get(key,default)` allows to set a default value without having to change too much around a null check - I fixed it with 
```diff
---  for entry in data['response']['games']:
+++ for entry in data['response'].get('games',{}):
```
Effectively using an empty dictionary if the key is not found.

Fix tested with an empty 'recently played' menu, which correctly displays an empty directory 🙂.

Instead of sending a PR to change the 3 code occurrences of this, I'll finish my refactoring with that fix included. Just writing this here in case I forget or the refactoring PR is refused or never happens.
